apiVersion: apps/v1
kind: Deployment
metadata:
  name: entities
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entities
  template:
    metadata:
      labels:
        app: entities
    spec:
      containers:
      - name: entities
        image: ampache-admin:update
        command:
        - "/bin/bash"
        - "-ecxv"
        - |
          echo "I am pod: entities"
          python3 /home/admin_update.py 5 10
        imagePullPolicy: Never

