---
# Remember to source your admin credentials before doing this!!!
- name: Creation of the whole infrastructure
  hosts: localhost
  gather_facts: no
  vars:
    custom_project_name: project_fcc
  
    base_sec_group: base_group
    key_pair: all-keys
  
    ubuntu_image: b5920bf6-28c6-4daa-aa62-4f78b8784220
    ubuntu_flavor: 4f96dd01-5edf-4946-9d37-e913d6a4c301 # 1024MB RAM with 5GB of memory;
    
    load_bal_name: load_bal 
    load_bal_network: load_net
    load_bal_sec_group: load_group

    web_server_name_1: webserver_1
    web_server_name_2: webserver_2
    web_server_sec_group: web_group

    database_name: database
    database_flavor: d3
    database_network: db_net
    database_sec_group: db_group
  
  
  tasks:
    - name: Launching - Instance - Load-balancer 
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ load_bal_name }}"
        image: "{{ ubuntu_image }}"
        flavor: "{{ ubuntu_flavor }}"
        network: "{{ load_bal_network }}" # on network 10.10.20.0/24
        key_name: "{{ key_pair }}"
        security_groups: 
          - "{{ base_sec_group }}"
          - "{{ web_server_sec_group  }}"
        floating_ips: 172.24.4.51
        userdata: "{{ lookup('file', 'userdata_loadbalancer.txt' )}}" 
    
    - name: Launching - Instance - Database
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ database_name }}"
        image: "{{ ubuntu_image }}"
        flavor: "{{ database_flavor }}"
        network: "{{ database_network }}" # on 10.10.30.0/24
        key_name: "{{ key_pair }}"
        security_groups: 
          - "{{ database_sec_group }}"
          - "{{ base_sec_group }}"
        floating_ips: 172.24.4.224
        userdata: "{{ lookup('file', 'userdata_database.txt' )}}"
    
    - name: Launching - Instance - First Web-server 
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ web_server_name_1 }}"
        image: "{{ ubuntu_image }}"
        flavor: "{{ ubuntu_flavor }}"
        network: "{{ load_bal_network }}" # on 10.10.20.0/24
        key_name: "{{ key_pair }}"
        security_groups: 
          - "{{ web_server_sec_group }}"
          - "{{ base_sec_group }}"
        floating_ips: 172.24.4.87
        userdata: "{{ lookup('file', 'userdata_server.txt' )}}"
    
    - name: Launching - Instance - Second Web-server 
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ web_server_name_2 }}"
        image: "{{ ubuntu_image }}"
        flavor: "{{ ubuntu_flavor }}"
        network: "{{ load_bal_network }}" # on 10.10.20.0/24
        key_name: "{{ key_pair }}"
        security_groups: 
          - "{{ web_server_sec_group }}" 
          - "{{ base_sec_group }}"
        floating_ips: 172.24.4.198
        userdata: "{{ lookup('file', 'userdata_server.txt' )}}"
        
