---
# Remember to source your admin credentials before doing this!!!
- name: Creation of the whole infrastructure
  hosts: localhost
  gather_facts: no
  vars:
    custom_project_name: deployment_fcc
  
    base_sec_group: ans_base_sec_group
    key_pair: all-keys
  
    ubuntu_image: b5920bf6-28c6-4daa-aa62-4f78b8784220
    ubuntu_flavor: 4f96dd01-5edf-4946-9d37-e913d6a4c301
    cirros_image: b00ea8f8-b2ab-44cd-a263-a0a82677e47d
    cirros_flavor: c1
    flavor_512: ds512M # with 5GB of memory; otherwise m1.tiny with 1 GB
    
    load_bal_name: ans_load_bal 
    load_bal_network: ans_net_first
    load_bal_sec_group: ans_load_bal_sec_group

    web_server_name_1: ans_web_server_1
    web_server_name_2: ans_web_server_2
    web_server_network: ans_net_second
    web_server_sec_group: ans_web_server_sec_group

    database_name: ans_database
    database_image: b00ea8f8-b2ab-44cd-a263-a0a82677e47d
    database_network: ans_net_third
    database_sec_group: ans_database_sec_group
  
  
  tasks:
    - name: Launching - Instance - Load-balancer 
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ load_bal_name }}"
        image: "{{ ubuntu_image }}"
        flavor: "{{ flavor_512 }}"
        network: "{{ load_bal_network }}" # on network 10.10.20.0/24
        key_name: "{{ key_pair }}"
        security_groups: 
          - "{{ base_sec_group }}"
          - "{{ web_server_sec_group  }}"
        auto_ip: yes
        delete_fip: yes
        userdata: |
          #cloud-config
          runcmd:
            - sudo sed -i '$ a nameserver 8.8.8.8' /etc/resolv.conf
            - sudo ip route add 10.10.30.0/24 via 10.10.20.3 
    
    - name: Launching - Instance - Database
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ database_name }}"
        image: "{{ ubuntu_image }}"
        flavor: "{{ ubuntu_flavor }}"
        network: "{{ database_network }}" # on 10.10.40.0/24
        key_name: "{{ key_pair }}"
        security_groups: 
          - "{{ database_sec_group }}"
          - "{{ base_sec_group }}"
        auto_ip: no
        userdata: "{{ lookup('file', 'userdata_database.txt' )}}"
    
    - name: Launching - Instance - First Web-server 
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ web_server_name_1 }}"
        image: "{{ ubuntu_image }}"
        flavor: "{{ ubuntu_flavor }}"
        network: "{{ web_server_network }}" # on 10.10.30.0/24
        key_name: "{{ key_pair }}"
        security_groups: 
          - "{{ web_server_sec_group }}"
          - "{{ base_sec_group }}"
        auto_ip: no
        userdata: "{{ lookup('file', 'userdata_server.txt' )}}"

    
    - name: Launching - Instance - Second Web-server 
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ web_server_name_2 }}"
        image: "{{ ubuntu_image }}"
        flavor: "{{ ubuntu_flavor }}"
        network: "{{ web_server_network }}" # on 10.10.30.0/24
        key_name: "{{ key_pair }}"
        security_groups: 
          - "{{ web_server_sec_group }}" 
          - "{{ base_sec_group }}"
        auto_ip: no
        userdata: "{{ lookup('file', 'userdata_server.txt' )}}"
           
    