---
# Remember to source your admin credentials before doing this!!!
- name: Creation of the whole infrastructure
  hosts: localhost
  gather_facts: no
  vars:
    custom_project_name: deployment_fcc

    net_first_name: ans_net_first
    net_second_name: ans_net_second
    net_third_name: ans_net_third
  
    base_sec_group: ans_base_sec_group
    key_pair: my_key
  
    load_bal_name: ans_load_bal
    load_bal_image: b00ea8f8-b2ab-44cd-a263-a0a82677e47d
    load_bal_flavor: 42
    load_bal_network: ans_net_first
    load_bal_sec_group: ans_load_bal_sec_group

    web_server_name_1: ans_web_server_1
    web_server_name_2: ans_web_server_2
    web_server_image: b00ea8f8-b2ab-44cd-a263-a0a82677e47d
    web_server_flavor: 42
    web_server_network: ans_net_second
    web_server_sec_group: ans_web_server_sec_group

    database_name: ans_database
    database_image: b00ea8f8-b2ab-44cd-a263-a0a82677e47d
    database_flavor: 42
    database_network: ans_net_third
    database_sec_group: ans_database_sec_group
  
  
  tasks:
    - name: Launching - Instance - Load-balancer
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ load_bal_name }}"
        image: "{{ load_bal_image }}"
        flavor: "{{ load_bal_flavor }}"
        network: "{{ load_bal_network }}"
        key_name: "{{ key_pair }}"
        security_groups: "{{ base_sec_group }}"
        auto_ip: yes
        delete_fip: yes
    
    - name: Launching - Instance - First Web-server
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ web_server_name_1 }}"
        image: "{{ web_server_image }}"
        flavor: "{{ web_server_flavor }}"
        network: "{{ web_server_network }}"
        key_name: "{{ key_pair }}"
        security_groups: "{{ web_server_sec_group }}", "{{ base_sec_group }}"
        auto_ip: no
    
    - name: Launching - Instance - Second Web-server
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ web_server_name_2 }}"
        image: "{{ web_server_image }}"
        flavor: "{{ web_server_flavor }}"
        network: "{{ web_server_network }}"
        key_name: "{{ key_pair }}"
        security_groups: "{{ web_server_sec_group }}", "{{ base_sec_group }}"
        auto_ip: no
    
    - name: Launching - Instance - Database
      openstack.cloud.server:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ database_name }}"
        image: "{{ database_image }}"
        flavor: "{{ database_flavor }}"
        network: "{{ database_network }}"
        key_name: "{{ key_pair }}"
        security_groups: "{{ database_sec_group }}", "{{ base_sec_group }}"
        auto_ip: no