---
# Remember to source your admin credentials before doing this!!!
- name: Creation of the network infrastructure
  hosts: localhost
  gather_facts: no
  vars:
    custom_project_name: deployment_fcc

    load_bal_network: load_net
    database_network: db_net
    
    load_bal_sub: load_sub
    database_sub: db_sub
  tasks:
    - name: Creation - Network - First network
      openstack.cloud.network:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ load_bal_network }}"
        external: no
        
    - name: Creation - Subnet - First network's subnet
      openstack.cloud.subnet:
        state: present
        network_name: "{{ load_bal_network }}"
        name: "{{ load_bal_sub }}"
        cidr: 10.10.20.0/24
        dns_nameservers:
         - 8.8.8.8
        host_routes:
         - destination: 10.10.20.0/24
           nexthop: 10.10.20.1

    - name: Creation - Network - Second network
      openstack.cloud.network:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ database_network }}"
        external: no
    
    - name: Creation - Subnet - Second network's subnet
      openstack.cloud.subnet:
        state: present
        network_name: "{{ database_network }}"
        name: "{{ database_sub }}"
        cidr: 10.10.30.0/24
        dns_nameservers:
         - 8.8.8.8
        host_routes:
         - destination: 10.10.30.0/24
           nexthop: 10.10.30.1  

    # Creates a router attached to the public network on an IPv4 subnet and one
    # internal subnet interface.
    - name: Creation - Router - Connection with external network 
      openstack.cloud.router:
        state: present
        name: routerA 
        network: public  # some public ip
        interfaces:
         - load_sub # 10.10.20.1

    # Create another router with two internal subnet interfaces
    - name: Creation - Router - Internal connection 1
      openstack.cloud.router:
        name: routerB
        interfaces:
         - net: load_net
           subnet: load_sub
           portip: 10.10.20.3
         - net: db_net
           subnet: db_sub # 10.10.30.1
           
    # Create another router with two internal subnet interfaces
    - name: Creation - Router - Database configuration
      openstack.cloud.router:
        state: present
        name: routerC
        network: public  # some public ip
        interfaces:
         - db_sub # 10.10.20.1

