---
# Remember to source your admin credentials before doing this!!!
- name: Creation of the network infrastructure
  hosts: localhost
  gather_facts: no
  vars:
    custom_project_name: deployment_fcc

    net_first_name: load_net
    net_second_name: web_net
    net_third_name: db_net
    
    sub_first_name: load_sub
    sub_second_name: web_sub
    sub_third_name: db_sub
  tasks:
    - name: Creation - Network - First network
      openstack.cloud.network:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ net_first_name }}"
        external: no
        
    - name: Creation - Subnet - First network's subnet
      openstack.cloud.subnet:
        state: present
        network_name: "{{ net_first_name }}"
        name: "{{ sub_first_name }}"
        cidr: 10.10.20.0/24
        dns_nameservers:
         - 8.8.8.8
        host_routes:
         - destination: 10.10.20.0/24
           nexthop: 10.10.20.1

    - name: Creation - Network - Second network
      openstack.cloud.network:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ net_second_name }}"
        external: no
    
    - name: Creation - Subnet - Second network's subnet
      openstack.cloud.subnet:
        state: present
        network_name: "{{ net_second_name }}"
        name: "{{ sub_second_name }}"
        cidr: 10.10.30.0/24
        dns_nameservers:
         - 8.8.8.8
        host_routes:
         - destination: 10.10.30.0/24
           nexthop: 10.10.30.1  
    
    - name: Creation - Network - Third network
      openstack.cloud.network:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ net_third_name }}"
        external: no
      
    - name: Creation - Subnet - Third network's subnet
      openstack.cloud.subnet:
        state: present
        network_name: "{{ net_third_name }}"
        name: "{{ sub_third_name }}"
        cidr: 10.10.40.0/24
        dns_nameservers:
         - 8.8.8.8
        host_routes:
         - destination: 10.10.40.0/24
           nexthop: 10.10.40.1  

    # Creates a router attached to the public network on an IPv4 subnet and one
    # internal subnet interface.
    - name: Creation - Router - Connection with external network 
      openstack.cloud.router:
        state: present
        name: routerA 
        network: public  # some public ip
        interfaces:
         - load_sub # 10.10.20.1

    # Create another router with two internal subnet interfaces
    - name: Creation - Router - Internal connection 1
      openstack.cloud.router:
        name: routerB
        interfaces:
         - net: load_net
           subnet: load_sub
           portip: 10.10.20.3
         - net: web_net
           subnet: web_sub # 10.10.30.1
           
    # Create another router with two internal subnet interfaces, with default gateway.
    - name: Creation - Router - Internal connection 2
      openstack.cloud.router:
        name: routerC
        interfaces:
         - net: web_net
           subnet: web_sub
           portip: 10.10.30.3
         - net: db_net
           subnet: db_sub # 10.10.40.1

