---
# Remember to source your admin credentials before doing this!!!
- name: Creation of the security groups with their rules
  hosts: localhost
  gather_facts: no
  vars:
    custom_project_name: project_fcc
    
    base_sec_group: base_group
    load_bal_sec_group: load_group
    web_server_sec_group: web_group
    database_sec_group: db_group
    
  tasks: 
    - name: Creation - Security group - Base ping and ssh
      openstack.cloud.security_group:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ base_sec_group }}"
        description: Base security group for ping and ssh 
  
    - name: Creation - Security group - Load balancer
      openstack.cloud.security_group:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ load_bal_sec_group }}"
        description: Security group for the load balancer
        
    - name: Creation - Security group - Web-server
      openstack.cloud.security_group:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ web_server_sec_group }}"
        description: Security group for web-servers
        
    - name: Creation - Security group - Database 
      openstack.cloud.security_group:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        name: "{{ database_sec_group }}"
        description: Security group for the database
        
    - name: Creation - Rule Ping, Security group - Base 
      openstack.cloud.security_group_rule:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        security_group: "{{ base_sec_group }}"
        direction: ingress
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0
    
    - name: Creation - Rule SSH, Security group - Base
      openstack.cloud.security_group_rule:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        security_group: "{{ base_sec_group }}"
        direction: ingress
        protocol: tcp
        ethertype: IPv4
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0

    - name: Creation - Rule HTTP, Security group - Web-server
      openstack.cloud.security_group_rule:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        security_group: "{{ web_server_sec_group }}"
        direction: ingress
        protocol: tcp
        ethertype: IPv4
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0
        
    - name: Creation - Rule SQL, Security group - Database
      openstack.cloud.security_group_rule:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        security_group: "{{ database_sec_group }}"
        direction: ingress
        protocol: tcp
        ethertype: IPv4
        port_range_min: 3306
        port_range_max: 3306
        remote_ip_prefix: 0.0.0.0/0
    
    - name: Creation - Rule NFS, Security group - Database
      openstack.cloud.security_group_rule:
        state: present
        auth:
          project_name: "{{ custom_project_name }}"
        security_group: "{{ database_sec_group }}"
        direction: ingress
        protocol: tcp
        ethertype: IPv4
        port_range_min: 2049
        port_range_max: 2049
        remote_ip_prefix: 0.0.0.0/0

    
    
